chore(deps): add missing dependencies `@babel/core` and `fs-extra` (#10143)
Was trying to isolate the Vite package to test its exports, but some of
its dependencies have missing dependencies that are getting in the way.
These ones are the easiest to fix.

```
~/esm-test/.pnp.cjs:19182
      Error.captureStackTrace(firstError);
            ^

Error: @redwoodjs/structure tried to access fs-extra, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: fs-extra
Required by: @redwoodjs/structure@file:./tarballs/redwoodjs-structure.tgz#./tarballs/redwoodjs-structure.tgz::hash=9b5cd1&locator=esm-test%40workspace%3A.
```