fix(deps): update prisma monorepo to v5.4.2 (#9294)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@prisma/client](https://www.prisma.io)
([source](https://togithub.com/prisma/prisma)) | [`5.3.1` ->
`5.4.2`](https://renovatebot.com/diffs/npm/@prisma%2fclient/5.3.1/5.4.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@prisma%2fclient/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@prisma%2fclient/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@prisma%2fclient/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@prisma%2fclient/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [@prisma/internals](https://www.prisma.io)
([source](https://togithub.com/prisma/prisma)) | [`5.3.1` ->
`5.4.2`](https://renovatebot.com/diffs/npm/@prisma%2finternals/5.3.1/5.4.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@prisma%2finternals/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@prisma%2finternals/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@prisma%2finternals/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@prisma%2finternals/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prisma](https://www.prisma.io)
([source](https://togithub.com/prisma/prisma)) | [`5.3.1` ->
`5.4.2`](https://renovatebot.com/diffs/npm/prisma/5.3.1/5.4.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prisma/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prisma/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prisma/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prisma/5.3.1/5.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

<details>
<summary>prisma/prisma (@&#8203;prisma/client)</summary>

[Compare
Source](https://togithub.com/prisma/prisma/compare/5.4.1...5.4.2)

Today, we are issuing the `5.4.2` patch release.

- [5.4.0 subquery has too many
columns](https://togithub.com/prisma/prisma/issues/21356)

[Compare
Source](https://togithub.com/prisma/prisma/compare/5.4.0...5.4.1)

Today, we are issuing the `5.4.1` patch release.

- [Invalid `….findMany()` invocation: The column `j1.id` does not exist
in the current
database.](https://togithub.com/prisma/prisma/issues/21352)

- [Planetscale driver: unsupported column type
NULL](https://togithub.com/prisma/prisma/issues/21369)

[Compare
Source](https://togithub.com/prisma/prisma/compare/5.3.1...5.4.0)

🌟 **Help us spread the word about Prisma by starring the repo or
[tweeting](https://twitter.com/intent/tweet?text=Check%20out%20the%20latest%20@&#8203;prisma%20release%20v5.4.0%20%F0%9F%9A%80%0D%0A%0D%0Ahttps://github.com/prisma/prisma/releases/tag/5.4.0)
about the release.** 🌟

drivers

We’re excited to announce
[Preview](https://www.prisma.io/docs/about/prisma/releases#preview)
support for the Neon and PlanetScale serverless database drivers. The
PlanetScale and Neon serverless database drivers allow Prisma to connect
to your database using protocols besides TCP — HTTP (PlanetScale) or
WebSockets (Neon).

To get started with the serverless database drivers, first enable the
`driverAdapters` Preview feature flag in your Prisma schema:

```prisma
// schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}
```

Next, to set up Prisma Client to use the serverless database drivers:

Install the Prisma adapter for PlanetScale and [PlanetScale serverless
database driver](https://togithub.com/planetscale/database-js), and
undici:

```bash
npm install @&#8203;prisma/adapter-planetscale @&#8203;planetscale/database undici
```

> Prisma ORM supports Node 16 and up. In Node 18 and up, `undici` is not
needed.

Ensure you update the host value in your connection string to
`aws.connect.psdb.cloud`. You can learn more about this
[here](https://planetscale.com/docs/tutorials/planetscale-serverless-driver#add-and-use-the-planetscale-serverless-driver-for-javascript-to-your-project).

```bash
DATABASE_URL='mysql://johndoe:strongpassword@aws.connect.psdb.cloud/clear_nightsky?sslaccept=strict'
```

Update your Prisma Client instance to use the PlanetScale database
driver:

```tsx
// Import required dependencies
import { connect } from '@&#8203;planetscale/database';
import { PrismaPlanetScale } from '@&#8203;prisma/adapter-planetscale';
import { PrismaClient } from '@&#8203;prisma/client';
import { fetch as undiciFetch } from 'undici';

// Initialize Prisma Client with the PlanetScale serverless database driver
const connection = connect({ url: connectionString, fetch: undiciFetch });
const adapter = new PrismaPlanetScale(connection);
const prisma = new PrismaClient({ adapter });
```

Install the Prisma adapter for Neon, [Neon serverless database
driver](https://togithub.com/neondatabase/serverless) and undici
(WebSockets):

```bash
npm install @&#8203;prisma/adapter-neon @&#8203;neondatabase/serverless undici
```

Update your Prisma Client instance to use the Neon serverless database
driver:

```tsx
// Import required dependencies
import { Pool, neonConfig } from '@&#8203;neondatabase/serverless';
import { PrismaNeon } from '@&#8203;prisma/adapter-neon';
import { PrismaClient } from '@&#8203;prisma/client';
import { WebSocket } from 'undici'

neonConfig.webSocketConstructor = WebSocket;

// Initialize Prisma Client with the Neon serverless database driver
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaNeon(pool);
const prisma = new PrismaClient({ adapter });
```

Let us know your feedback about the
[Neon](https://togithub.com/prisma/prisma/discussions/21346) or
[Planetscale](https://togithub.com/prisma/prisma/discussions/21347)
serverless database drivers in the linked GitHub discussions. Create a
[bug
report](https://togithub.com/prisma/prisma/issues/new?assignees=\&labels=kind/bug\&projects=\&template=bug_report.yml)
if you run into any issues.

[Turso](https://turso.tech/) is an edge-hosted, distributed database
that's based on [libSQL](https://turso.tech/libsql), an open-source and
open-contribution fork of SQLite, enabling you to bring data closer to
your application and minimize query latency.

Since support for Turso is in Early Access, there may be some rough
edges which we’re still working on it to improve the API and overall
support. Additionally, it is behind the `driverAdapters` Preview feature
flag. Enable it to get started using Turso in your project:

```groovy
// schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}
```

Next, install the Prisma Client adapter for Turso and the `libSQL`
database client

```bash
npm install @&#8203;prisma/adapter-libsql @&#8203;libsql/client
```

Update your Prisma Client instance:

```tsx
// Import required dependencies
import { PrismaClient } from '@&#8203;prisma/client'
import { PrismaLibSQL } from '@&#8203;prisma/adapter-libsql'
import { createClient } from '@&#8203;libsql/client'

// Create a new instance of the libSQL database client
const libsql = createClient({
  // @&#8203;ts-expect-error
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN
})

// Create a Prisma "adapter" for libSQL
const adapter = new PrismaLibSQL(libsql)
// Pass the adapter option to the Prisma Client instance
const prisma = new PrismaClient({ adapter })
```

You can learn more on how to use Prisma together with Turso in the
[announcement blog
post](https://www.prisma.io/blog/prisma-turso-ea-support-rXGd_Tmy3UXX).

Try it out! [Let us know what you
think](https://togithub.com/prisma/prisma/discussions/21345) and create
a [bug
report](https://togithub.com/prisma/prisma/issues/new?assignees=\&labels=kind/bug\&projects=\&template=bug_report.yml)
if you run into any issues.

In our continued efforts to make Prisma Client faster, we identified and
improved the performance of different types of queries.

We made the following improvements to relation filters:

- Removed an unnecessary `INNER JOIN` used in relation filter queries
(Big thank you to [@&#8203;KhooHaoYit](https://togithub.com/KhooHaoYit)
for helping out)
- Use of `LEFT JOIN`'s for to-one relations. Previously, Prisma made use
of sub-queries to fetch data.

**Example Prisma Client query**

```tsx
prisma.comment.findMany({
  where: {
    post: {
      author: {
        name: "John"
      }
    }
  }
})
```

**Before 5.4.0**

```sql
SELECT
  "Comment"."id"
FROM
  "Comment"
WHERE
  ("Comment"."id") IN (
    SELECT
      "t0"."id"
    FROM
      "Comment" AS "t0"
      INNER JOIN "Post" AS "j0" ON ("j0"."id") = ("t0"."postId")
    WHERE
      (
        ("j0"."id") IN (
          SELECT
            "t1"."id"
          FROM
            "Post" AS "t1"
            INNER JOIN "User" AS "j1" ON ("j1"."id") = ("t1"."userId")
          WHERE
            (
              "j1"."name" = $ 1
              AND "t1"."id" IS NOT NULL
            )
        )
        AND "t0"."id" IS NOT NULL
      )
  );
```

**After 5.4.0**

```sql
SELECT
  "Comment"."id"
FROM
  "Comment"
  LEFT JOIN "Post" AS "j1" ON ("j1"."id") = ("Comment"."postId")
  LEFT JOIN "User" AS "j2" ON ("j2"."id") = ("j1"."userId")
WHERE
  (
    "j2"."name" = $ 1
    AND ("j2"."id" IS NOT NULL)
    AND ("j1"."id" IS NOT NULL)
  );
```

If you’re interested in more details on the relation query filter
improvements, you can take a look at [this pull
request](https://togithub.com/prisma/prisma-engines/pull/4235).

Previously, when an enum value was used in a query, our Postgres driver
would make additional queries to resolve the enum types that were used.

In this release, we’re making improvements by casting enums to `TEXT` to
avoid the additional roundtrips when resolving the types.

This change should have the most impact if you’re using `pgBouncer` or
if you’re running Prisma in a serverless environment, where our Postgres
driver can’t cache enum types information.

**Prisma schema**

```groovy
model User {
  id   Int  @&#8203;id @&#8203;default(cuid())
  role Role
}

enum Role {
  User
  Admin
}
```

**Prisma Client query**

```tsx
await prisma.user.findMany({
  where: {
    role: "Admin"
  }
})
```

**Before 5.4.0**

```sql
-- Internal driver query
SELECT t.typname, t.typtype, t.typelem, r.rngsubtype, t.typbasetype, n.nspname, t.typrelid FROM pg_catalog.pg_type t LEFT OUTER JOIN pg_catalog.pg_range r ON r.rngtypid = t.oid INNER JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1;

-- Internal driver query
SELECT enumlabel FROM pg_catalog.pg_enum WHERE enumtypid = $1 ORDER BY enumsortorder;

-- Prisma Client query
SELECT id, role FROM "User" WHERE role = $1;
```

**After 5.4.0**

```sql
-- Prisma Client query
SELECT id, role::text FROM "User" WHERE role = CAST($1::text AS "Role);
```

We optimized the `deleteMany` operation by:

- Removing all `SELECT` queries used to fetch data that would be used as
input for the `DELETE` operation. In some cases, this also improves
index usage.
- Removing the transaction previously used as it’s now a single atomic
operation.

**Prisma Client query**

```tsx

await prisma.post.deleteMany({
  where: {
    id: {
      gt: 1,
      lt: 10,
    }
  }
})
```

**Before 5.4.0**

```sql
BEGIN
SELECT id FROM "Post" WHERE id > 1 AND id < 10;
SELECT id FROM "Post" WHERE id > 1 AND id < 10 AND id IN (<...select ids>);
DELETE FROM "Post" WHERE id IN (<...select ids>) AND id > 1 AND id < 10;
COMMIT
```

**After 5.4.0**

```sql
DELETE FROM "Post" WHERE id > 1 AND id < 10;
```

We improved the `upsert` operation ([non-native database
upsert](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#database-upserts))
by removing a redundant `SELECT` query:

**Prisma Client query**

```tsx
await prisma.user.upsert({
  where: { email: "john@doe.com" },
  create: { email: "john@doe.com", firstName: "John" },
  update: { firstName: "Johnny" },
})
```

**Before 5.4.0**

```sql
SELECT `User`.`id` FROM `User` WHERE `User`.`email` = ?;
SELECT `User`.`id` FROM `User` WHERE `User`.`email` = ?;
UPDATE `prisma`.`User` SET `firstName` = ? WHERE `prisma`.`User`.`id` IN (?) AND `prisma`.`User`.`email` = ?;
SELECT `User`.`id` FROM `User` WHERE `User`.`id` = ?;
```

**After 5.4.0**

```sql
SELECT `User`.`id` FROM `User` WHERE `User`.`email` = ?;
UPDATE `prisma`.`User` SET `firstName` = ? WHERE `prisma`.`User`.`id` IN (?) AND `prisma`.`User`.`email` = ?;
SELECT `User`.`id` FROM `User` WHERE `User`.`id` = ?;
```

- [Unnecessary `SELECT` may be generated by
`upsert()`](https://togithub.com/prisma/prisma/issues/5686)
- [Inefficient deleteMany query
generation](https://togithub.com/prisma/prisma/issues/7232)
- [Prisma can generate an overly complex and inefficient query in some
cases](https://togithub.com/prisma/prisma/issues/7894)
- [`deleteMany`
optimisation](https://togithub.com/prisma/prisma/issues/8239)
- [CockroachDB: Highly Variable Query Response
Times](https://togithub.com/prisma/prisma/issues/11317)
- [Extremely poor relation where clause
query](https://togithub.com/prisma/prisma/issues/14688)
- [Enums loaded as part of transaction after `UPDATE`, slowing down
transaction.](https://togithub.com/prisma/prisma/issues/14955)
- [ MongoDB `deleteMany` seems to send 2 identical read queries first
before triggering the actual
delete](https://togithub.com/prisma/prisma/issues/15085)
- [Query validation messages reference color output even if colors are
not enabled](https://togithub.com/prisma/prisma/issues/17706)
- [Prisma generates unnecessary subquery, which is
inefficient](https://togithub.com/prisma/prisma/issues/17879)
- [Unnecessary INNER JOIN when doing nested
queries](https://togithub.com/prisma/prisma/issues/18343)
- [Semver checks for yarn and typescript could potentially
fail](https://togithub.com/prisma/prisma/issues/18751)
- [Prisma overrides type caching when in PGBouncer mode, causing 9,000
enum queries per second on a production
system](https://togithub.com/prisma/prisma/issues/19325)
- [deleteMany generates double WHERE
filter](https://togithub.com/prisma/prisma/issues/19950)
- [Prisma generate command crashes with `RustPanic: RuntimeError:
panicked at 'internal error: entered unreachable code',
query-engine/prisma-models/src/field/scalar.rs:93:50`](https://togithub.com/prisma/prisma/issues/20037)
- [Duplicated keys in `metrics`
properties](https://togithub.com/prisma/prisma/issues/21069)
- [Prisma Client extension with method override and `jest-mock-extended`
or `vitest-mock-extended` expects `never` input
](https://togithub.com/prisma/prisma/issues/21136)

- [Auto-completion suggests attributes already present
](https://togithub.com/prisma/language-tools/issues/1326)
- [Quick Fix: when `@@&#8203;schema` is defined in a block without the
`schemas`
attribute](https://togithub.com/prisma/language-tools/issues/1333)

- [CockroachDB: get_columns can hit inefficiency inside
pg_class](https://togithub.com/prisma/prisma-engines/issues/4250)

Huge thanks to [@&#8203;onichandame](https://togithub.com/onichandame),
[@&#8203;fqazi](https://togithub.com/fqazi),
[@&#8203;KhooHaoYit](https://togithub.com/KhooHaoYit),
[@&#8203;alencardc](https://togithub.com/alencardc),
[@&#8203;Oreilles](https://togithub.com/Oreilles),
[@&#8203;christianledgard](https://togithub.com/christianledgard),
[@&#8203;skyzh](https://togithub.com/skyzh),
[@&#8203;alula](https://togithub.com/alula),
[@&#8203;michaelpoellath](https://togithub.com/michaelpoellath),
[@&#8203;RobertCraigie](https://togithub.com/RobertCraigie),
[@&#8203;icanipa](https://togithub.com/icanipa),
[@&#8203;jiashengguo](https://togithub.com/jiashengguo),
[@&#8203;stephenwade](https://togithub.com/stephenwade),
[@&#8203;darthmaim](https://togithub.com/darthmaim),
[@&#8203;ludralph](https://togithub.com/ludralph),
[@&#8203;Gerschtli](https://togithub.com/Gerschtli),
[@&#8203;andyjy](https://togithub.com/andyjy) for helping!

If you're interested in joining our growing team to help empower
developers to build data-intensive applications, Prisma is the place for
you.

We're currently hiring for the following roles:

- [Software
Engineer](https://boards.greenhouse.io/prisma/jobs/6948042002)
- [Senior Software Engineer
(Rust)](https://boards.greenhouse.io/prisma/jobs/6940273002)
- [Engineering Manager: Prisma Data
Platform](https://boards.greenhouse.io/prisma/jobs/6927046002)

Feel free to read the job descriptions and apply using the links
provided.

</details>

---

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/redwoodjs/redwood).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy44LjEiLCJ1cGRhdGVkSW5WZXIiOiIzNy44LjEiLCJ0YXJnZXRCcmFuY2giOiJtYWluIn0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>