fix cli yarn rw destroy graphiql command (#7831)
Currently `yarn rw destroy graphiql` throws

```
TypeError: (0 , _graphiql.getOutputPath) is not a function
    at Object.handler (<project_path>/node_modules/@redwoodjs/cli/dist/commands/destroy/graphiql/graphiql.js:32:44)
    at <project_path>/node_modules/yargs/build/index.cjs:1:8993
    at <project_path>/node_modules/yargs/build/index.cjs:1:4949
error Command failed with exit code 1.
```
This is because `getOutputPath` is imported from

`import { getOutputPath } from '../../setup/graphiql/graphiql`

instead of

`import { getOutputPath } from '../../setup/graphiql/graphiqlHelpers'`

I guess this broke when the graphiql setup logic was refactored.

regards