Adds 'use client' to Metadata so that it always runs in the client
Otherwise throws a TypeError when serving the site, `React.createContext is not a function`